schema_version: '2.0'
title: Radosavljevic2009 Bioterroristattack Panicprotection 1 Lab
description: 'This model is from the article: Epidemics of panic during a bioterrorist
  attack--a mathematical model. It can be used to explore systemsbiology radosavljevic2009
  bioterroristattack panicprotec BioModels0000000836 dynamics and compare simulation
  behavior across conditions.'
models:
- alias: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.state
  to:
  - visualisation.systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model_state
- from: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.summary
  to:
  - visualisation.systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model_summary
- from: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.species_labels
  to:
  - visualisation.systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model_species_labels
runtime:
  duration: 1.0
  communication_step: 0.1
  initial_inputs: {}
tags:
- systemsbiology
- sbml
- biomodels_ebi
- faithful
- curated
io:
  inputs:
  - name: initial_protection_prevention_intensity
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.initial_protection_prevention_intensity
    label: Initial Protection Prevention Intensity
    description: Source state initial condition exposed as a model-specific control
      because no explicit intervention parameter is identifiable. Maps to SBML symbol
      `P`.
  - name: initial_panic_intensity
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.initial_panic_intensity
    label: Initial Panic Intensity
    description: Source state initial condition exposed as a model-specific control
      because no explicit intervention parameter is identifiable. Maps to SBML symbol
      `S`.
  outputs:
  - name: state
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.state
  - name: summary
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.summary
  - name: species_labels
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.species_labels
  - name: protection_prevention_intensity
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.protection_prevention_intensity
  - name: panic_intensity
    maps_to: systemsbiology_sbml_radosavljevic2009_bioterroristattack_panicprotec_biomd0000000836_model.panic_intensity
