# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Sass2009 - Approach to an α-synuclein-based BST model of Parkinson's disease."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Sass2009ApproachToAnSynucleinBasedBstModeBiomd0000000575Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Sass2009 - Approach to an α-synuclein-based BST model of Parkinson's disease."""

    _SBML_ID = 'BIOMD0000000575'
    _TITLE = "Sass2009 - Approach to an α-synuclein-based BST model of Parkinson's disease"
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['Protofibril', 'Fibril', 'Lewy_body', 'Dopamine', 'OH', 'OH_radical', 'H2O2', 'DA_quinone', 'Ubiquitin', 'E1', 'Ub_E1', 'UbcH8', 'UbcH8_Ub', 'Parkin', 'Parkin_sub', 'Parkin_synphilin_1', 'Parkin_synphilin_1_ub', 'Parkin_sub_ub4', 'Fragments', 'UCH_L1', 'L_Dopa', 'DOPAL', 'DOPAC', 'GSH', 'GSSG', 'Fe2', 'Fe3', 'UbcH8ub2', 'UbcH8ub3', 'UbcH8ub4', 'UbcH13_Uev1a', 'UbcH13_Uev1a_ub', 'asyn_UCH_L1', 'asyn_ub', 'Protofibril_UCH_L1', 'Protofibril_Ub', 'UCH_L1_asyn_ub4', 'Hsc70_asyn', 'Hsc70_Protofibril', 'Hsc70_fibril', 'Hsc70', 'DA_S_parkin', 'O2', 'DA_GSH', 'Neuromelanin', 'Neuromelanin_ntox_Fe3', 'Alpha_synuclein', 'ATP', 'Synphilin_1', 'Substrate', 'TH', 'L_Tyr', 'CO2', 'Neurotoxins', 'Bioamines', 'VMAT2', 'O2_0', 'MAO', 'NH3', 'ALDH', 'NAD', 'NADH', 'Catalase', 'H2O', 'Gluta_per', 'Gluta_red', 'DDC', 'Preautophagosome_membrane', 'SOD', 'Cysteine', 'V_DA', 'V_ntox_ba', 'Vesicle_0', 'Autophagosome_0', 'Proteasome_0', 'Lysosome_0']
    _SPECIES_LABELS = {'Protofibril': 'Protofibril', 'Fibril': 'Fibril', 'Lewy_body': 'Lewy_body', 'Dopamine': 'Dopamine', 'OH': 'OH-', 'OH_radical': 'OH_radical', 'H2O2': 'H2O2', 'DA_quinone': 'DA_quinone', 'Ubiquitin': 'Ubiquitin', 'E1': 'E1', 'Ub_E1': 'Ub-E1', 'UbcH8': 'UbcH8', 'UbcH8_Ub': 'UbcH8-Ub', 'Parkin': 'Parkin', 'Parkin_sub': 'Parkin-sub', 'Parkin_synphilin_1': 'Parkin-synphilin-1', 'Parkin_synphilin_1_ub': 'Parkin-synphilin-1-ub', 'Parkin_sub_ub4': 'Parkin-sub-ub4', 'Fragments': 'Fragments', 'UCH_L1': 'UCH-L1', 'L_Dopa': 'L-Dopa', 'DOPAL': 'DOPAL', 'DOPAC': 'DOPAC', 'GSH': 'GSH', 'GSSG': 'GSSG', 'Fe2': 'Fe2+', 'Fe3': 'Fe3+', 'UbcH8ub2': 'UbcH8ub2', 'UbcH8ub3': 'UbcH8ub3', 'UbcH8ub4': 'UbcH8ub4', 'UbcH13_Uev1a': 'UbcH13/Uev1a', 'UbcH13_Uev1a_ub': 'UbcH13/Uev1a-ub', 'asyn_UCH_L1': 'asyn-UCH-L1', 'asyn_ub': 'asyn-ub', 'Protofibril_UCH_L1': 'Protofibril-UCH-L1', 'Protofibril_Ub': 'Protofibril-Ub', 'UCH_L1_asyn_ub4': 'UCH-L1-asyn-ub4', 'Hsc70_asyn': 'Hsc70-asyn', 'Hsc70_Protofibril': 'Hsc70-Protofibril', 'Hsc70_fibril': 'Hsc70-fibril', 'Hsc70': 'Hsc70', 'DA_S_parkin': 'DA-S-parkin', 'O2': 'O2-', 'DA_GSH': 'DA-GSH', 'Neuromelanin': 'Neuromelanin', 'Neuromelanin_ntox_Fe3': 'Neuromelanin-ntox-Fe3+', 'Alpha_synuclein': 'Alpha_synuclein', 'ATP': 'ATP', 'Synphilin_1': 'Synphilin-1', 'Substrate': 'Substrate', 'TH': 'TH', 'L_Tyr': 'L-Tyr', 'CO2': 'CO2', 'Neurotoxins': 'Neurotoxins', 'Bioamines': 'Bioamines', 'VMAT2': 'VMAT2', 'O2_0': 'O2', 'MAO': 'MAO', 'NH3': 'NH3', 'ALDH': 'ALDH', 'NAD': 'NAD+', 'NADH': 'NADH', 'Catalase': 'Catalase', 'H2O': 'H2O', 'Gluta_per': 'Gluta_per', 'Gluta_red': 'Gluta_red', 'DDC': 'DDC', 'Preautophagosome_membrane': 'Preautophagosome_membrane', 'SOD': 'SOD', 'Cysteine': 'Cysteine', 'V_DA': 'V-DA', 'V_ntox_ba': 'V-ntox-ba', 'Vesicle_0': 'Vesicle', 'Autophagosome_0': 'Autophagosome', 'Proteasome_0': 'Proteasome', 'Lysosome_0': 'Lysosome'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_model_state_nad': ('NAD', 1.5, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `NAD`.'), 'initial_model_state_atp': ('ATP', 2.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `ATP`.'), 'initial_nadh': ('NADH', 1.5, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `NADH`.'), 'initial_v_da': ('V_DA', 10.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `V_DA`.'), 'initial_l_tyr': ('L_Tyr', 5.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `L_Tyr`.'), 'initial_parkin_synphilin_1_ub': ('Parkin_synphilin_1_ub', 2.5, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Parkin_synphilin_1_ub`.')}
    _HEADLINE_OUTPUTS = {'nad': ('NAD', 'native SBML value', 'NAD+. Maps to SBML symbol `NAD`.'), 'atp': ('ATP', 'native SBML value', 'ATP. Maps to SBML symbol `ATP`.'), 'nadh': ('NADH', 'native SBML value', 'NADH. Maps to SBML symbol `NADH`.'), 'v_da': ('V_DA', 'native SBML value', 'V-DA. Maps to SBML symbol `V_DA`.'), 'l_tyr': ('L_Tyr', 'native SBML value', 'L-Tyr. Maps to SBML symbol `L_Tyr`.'), 'parkin_synphilin_1_ub': ('Parkin_synphilin_1_ub', 'native SBML value', 'Parkin-synphilin-1-ub. Maps to SBML symbol `Parkin_synphilin_1_ub`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/BIOMD0000000575.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
