# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Emiola2016 - Crosstalk between the lipopolysaccharide and phospholipid pathways during outer membrane biosynthesis,."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Emiola2016CrosstalkBetweenTheLipopolysaccharModel1601080000Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Emiola2016 - Crosstalk between the lipopolysaccharide and phospholipid pathways during outer membrane biosynthesis,."""

    _SBML_ID = 'MODEL1601080000'
    _TITLE = 'Emiola2016 - Crosstalk between the lipopolysaccharide and phospholipid pathways during outer membrane biosynthesis,'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['LpxA', 'P1', 'UDP_GlcNac', 'LpxC', 'promoter_LpxC', 'P2', 'Beta_hydroxymyristoylACP', 'ACP', 'LpxD', 'P3', 'LpxH', 'P4', 'lipidAdisaccharide', 'LpxB', 'LpxK', 'P6', 'KdtA', 'promoter_KdtA', 'P7', 'LpxL', 'P8', 'LpxM', 'lipidA', 'MsbA', 'lipidA_OM', 'FtsH', 'FtsH_act_lpxc', 'FtsH_act_kdta', 'CMP_KDO', 'lipidA_un', 'b_oh_10', 'trans_10', 'FabA', 'FabZ', 'C10_1', 'C10', 'FabI', 'FabB', 'ketoacyl_12', 'FabF', 'B_OH_12', 'FabG', 'trans_12', 'C12', 'ketoacyl_12_1', 'B_OH_12_1', 'trans_12_1', 'C12_1', 'ketoacyl_14', 'trans_14', 'C14', 'ketoacyl_14_1', 'B_OH_14_1', 'trans_14_1', 'C14_1', 'ketoacyl_16', 'B_OH_16', 'trans_16', 'C16', 'ketoacyl_16_1', 'B_OH_16_1', 'trans_16_1', 'C16_1', 'ketoacyl_18_1', 'B_OH_18_1', 'trans_18_1', 'C18_1', 'PlsB', 'G3P', 'PlsC', 'palmitic', 'vaccenic', 'palmitoleic', 'LpxK_act', 'proA_unreg', 'FadR', 'proA', 'FabR', 'FabR_0', 'FadR_proA', 'inact_proA1', 'inact_proA2', 'FabH', 'acetyl_CoA', 'FadR_0', 'proB_unreg', 'FadR_proB', 'proB', 'inact_proB1', 'inact_proB2']
    _SPECIES_LABELS = {'LpxA': 'LpxA', 'P1': 'P1', 'UDP_GlcNac': 'UDP-GlcNac', 'LpxC': 'LpxC', 'promoter_LpxC': 'promoter-LpxC', 'P2': 'P2', 'Beta_hydroxymyristoylACP': 'Beta-hydroxymyristoylACP', 'ACP': 'ACP', 'LpxD': 'LpxD', 'P3': 'P3', 'LpxH': 'LpxH', 'P4': 'P4', 'lipidAdisaccharide': 'lipidAdisaccharide', 'LpxB': 'LpxB', 'LpxK': 'LpxK', 'P6': 'P6', 'KdtA': 'KdtA', 'promoter_KdtA': 'promoter-KdtA', 'P7': 'P7', 'LpxL': 'LpxL', 'P8': 'P8', 'LpxM': 'LpxM', 'lipidA': 'lipidA', 'MsbA': 'MsbA', 'lipidA_OM': 'lipidA_OM', 'FtsH': 'FtsH', 'FtsH_act_lpxc': 'FtsH_act_lpxc', 'FtsH_act_kdta': 'FtsH_act_kdta', 'CMP_KDO': 'CMP-KDO', 'lipidA_un': 'lipidA_un', 'b_oh_10': 'b-oh-10', 'trans_10': 'trans-10', 'FabA': 'FabA', 'FabZ': 'FabZ', 'C10_1': 'C10:1', 'C10': 'C10', 'FabI': 'FabI', 'FabB': 'FabB', 'ketoacyl_12': 'ketoacyl-12', 'FabF': 'FabF', 'B_OH_12': 'B-OH-12', 'FabG': 'FabG', 'trans_12': 'trans-12', 'C12': 'C12', 'ketoacyl_12_1': 'ketoacyl-12:1', 'B_OH_12_1': 'B-OH-12:1', 'trans_12_1': 'trans-12:1', 'C12_1': 'C12:1', 'ketoacyl_14': 'ketoacyl-14', 'trans_14': 'trans-14', 'C14': 'C14', 'ketoacyl_14_1': 'ketoacyl-14:1', 'B_OH_14_1': 'B-OH-14:1', 'trans_14_1': 'trans-14:1', 'C14_1': 'C14:1', 'ketoacyl_16': 'ketoacyl-16', 'B_OH_16': 'B-OH-16', 'trans_16': 'trans-16', 'C16': 'C16', 'ketoacyl_16_1': 'ketoacyl-16:1', 'B_OH_16_1': 'B-OH-16:1', 'trans_16_1': 'trans-16:1', 'C16_1': 'C16:1', 'ketoacyl_18_1': 'ketoacyl-18:1', 'B_OH_18_1': 'B-OH-18:1', 'trans_18_1': 'trans-18:1', 'C18_1': 'C18:1', 'PlsB': 'PlsB', 'G3P': 'G3P', 'PlsC': 'PlsC', 'palmitic': 'palmitic', 'vaccenic': 'vaccenic', 'palmitoleic': 'palmitoleic', 'LpxK_act': 'LpxK_act', 'proA_unreg': 'proA_unreg', 'FadR': 'FadR*', 'proA': 'proA', 'FabR': 'FabR*', 'FabR_0': 'FabR', 'FadR_proA': 'FadR/proA', 'inact_proA1': 'inact_proA1', 'inact_proA2': 'inact_proA2', 'FabH': 'FabH', 'acetyl_CoA': 'acetyl-CoA', 'FadR_0': 'FadR', 'proB_unreg': 'proB_unreg', 'FadR_proB': 'FadR/proB', 'proB': 'proB', 'inact_proB1': 'inact_proB1', 'inact_proB2': 'inact_proB2'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_promoter_lpx_c': ('promoter_LpxC', 2.47841609427273e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `promoter_LpxC`.'), 'initial_promoter_kdt_a': ('promoter_KdtA', 2.47841609427273e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `promoter_KdtA`.'), 'initial_acetyl_co_a': ('acetyl_CoA', 4.95683218854545, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `acetyl_CoA`.'), 'initial_udp_glc_nac': ('UDP_GlcNac', 4.95683218854545, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `UDP_GlcNac`.'), 'initial_cmp_kdo': ('CMP_KDO', 4.95683218854545, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CMP_KDO`.'), 'initial_fad_r': ('FadR_0', 0.000731132747810454, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `FadR_0`.')}
    _HEADLINE_OUTPUTS = {'promoter_lpx_c': ('promoter_LpxC', 'native SBML value', 'promoter-LpxC. Maps to SBML symbol `promoter_LpxC`.'), 'promoter_kdt_a': ('promoter_KdtA', 'native SBML value', 'promoter-KdtA. Maps to SBML symbol `promoter_KdtA`.'), 'acetyl_co_a': ('acetyl_CoA', 'native SBML value', 'acetyl-CoA. Maps to SBML symbol `acetyl_CoA`.'), 'udp_glc_nac': ('UDP_GlcNac', 'native SBML value', 'UDP-GlcNac. Maps to SBML symbol `UDP_GlcNac`.'), 'cmp_kdo': ('CMP_KDO', 'native SBML value', 'CMP-KDO. Maps to SBML symbol `CMP_KDO`.'), 'fad_r': ('FadR_0', 'native SBML value', 'FadR. Maps to SBML symbol `FadR_0`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL1601080000.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
