schema_version: '2.0'
title: Lockwood2006 Alzheimer S Disease Pbpk Lab
description: Lockwood2006 - AlzheimersDisease PBPKmodel A mathematical model to predict
  theeffectiveness of CI-1017 (muscarinic agonist) for Alzheimer'sdisease by evaluating
  changes in ADAS-cog score. It can be used to explore systemsbiology lockwood2006
  alzheimer s disease pbpk dynamics and compare simulation behavior across conditions.
models:
- alias: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.state
  to:
  - visualisation.systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model_state
- from: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.summary
  to:
  - visualisation.systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model_summary
- from: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.species_labels
  to:
  - visualisation.systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model_species_labels
runtime:
  duration: 1.0
  communication_step: 0.1
  initial_inputs: {}
tags:
- neuroscience
- pharmacology
- systemsbiology
- sbml
- biomodels_ebi
- faithful
- curated
io:
  inputs: []
  outputs:
  - name: state
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.state
  - name: summary
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.summary
  - name: species_labels
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.species_labels
  - name: pd_ce_p
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.pd_ce_p
  - name: pd_ce_a
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.pd_ce_a
  - name: model_inactive
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.model_inactive
  - name: model_active_u_shaped
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.model_active_u_shaped
  - name: model_active_sigmoidal
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.model_active_sigmoidal
  - name: model_active_linear
    maps_to: systemsbiology_sbml_lockwood2006_alzheimer_s_disease_pbpk_model_biomd0000000673_model.model_active_linear
