# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Birtwistle2007_ErbB_Signalling."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Birtwistle2007ErbbSignallingBiomd0000000175Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Birtwistle2007_ErbB_Signalling."""

    _SBML_ID = 'BIOMD0000000175'
    _TITLE = 'Birtwistle2007_ErbB_Signalling'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['E1', 'E2', 'E3', 'E4', 'E_E1', 'H_E3', 'H_E4', 'E11', 'E12', 'E23', 'E34', 'E24', 'E44', 'E11P', 'E12P', 'E23P', 'E34P', 'E24P', 'E44P', 'G', 'S', 'I', 'R', 'O', 'A', 'E11G', 'E11S', 'E11R', 'E12G', 'E12S', 'E12R', 'E23G', 'E23S', 'E23I', 'E23R', 'E34G', 'E34S', 'E34I', 'E34R', 'E24G', 'E24S', 'E24I', 'E24R', 'E44G', 'E44S', 'E44I', 'E44R', 'SigG', 'SigS', 'SigI', 'SigR', 'SigA', 'SigSP', 'SigAP', 'SigG_O', 'SigG_A', 'SigSP_G', 'SigAP_S', 'SigAP_I', 'SigAP_R', 'Empty', 'P3_A', 'P2', 'P3', 'Akt', 'RsD', 'RsT', 'SigRP', 'Raf', 'Rafstar', 'MEK', 'MEKstar', 'ERK', 'ERKstar', 'OP', 'AP', 'A_SigG_O', 'SigA_G', 'SigA_G_O', 'SigO', 'E13', 'E14', 'E13P', 'E14P', 'E13G', 'E13S', 'E13I', 'E13R', 'E14G', 'E14S', 'E14I', 'E14R', 'T', 'E11T', 'E12T', 'E23T', 'E34T', 'E24T', 'E44T', 'E13T', 'E14T', 'SigT', 'E1_PT', 'E2_PT', 'E4_PT', 'E_E1_PT', 'H_E4_PT', 'Aktstar', 'SigAP_T', 'E', 'H', 'fint', 'pERK', 'ERK_MEKstar', 'pERK_MEKstar', 'pERK_ERKpase', 'ERKpase', 'ERKstar_ERKpase', 'norm_Akt_star', 'norm_Erk_star']
    _SPECIES_LABELS = {'E1': 'ErbB1', 'E2': 'ErbB2', 'E3': 'ErbB3', 'E4': 'ErbB4', 'E_E1': 'EGF-ErbB1', 'H_E3': 'HRG-ErbB3', 'H_E4': 'HRG-ErbB4', 'E11': '(EGF-ErbB1)2', 'E12': 'EGF-ErbB1-ErbB2', 'E23': 'HRG-ErbB3-ErbB2', 'E34': '(HRG-ErbB3/4)2', 'E24': 'HRG-Erb4-ErbB2', 'E44': '(HRG-Erb4)2', 'E11P': 'E11_p', 'E12P': 'E12_p', 'E23P': 'E23_p', 'E34P': 'E34_p', 'E24P': 'E24_p', 'E44P': 'E44_p', 'G': 'Grb2', 'S': 'Shc', 'I': 'PI-3K', 'R': 'RasGAP', 'O': 'SOS', 'A': 'Gab1', 'E11G': 'E11-Grb2', 'E11S': 'E11-Shc', 'E11R': 'E11-RasGAP', 'E12G': 'E12-Grb2', 'E12S': 'E12-Shc', 'E12R': 'E12-RasGAP', 'E23G': 'E23-Grb2', 'E23S': 'E23-Shc', 'E23I': 'E23-PI-3K', 'E23R': 'E23-RasGAP', 'E34G': 'E34-Grb2', 'E34S': 'E34-Shc', 'E34I': 'E34-PI-3K', 'E34R': 'E34-RasGAP', 'E24G': 'E24-Grb2', 'E24S': 'E24-Shc', 'E24I': 'E24-PI-3K', 'E24R': 'E24-RasGAP', 'E44G': 'E44-Grb2', 'E44S': 'E44-Shc', 'E44I': 'E44-PI-3K', 'E44R': 'E44-RasGAP', 'SigG': 'Sum Grb2', 'SigS': 'Sum Shc', 'SigI': 'Sum PI-3K', 'SigR': 'Sum RasGAP', 'SigA': 'Sum Gab1', 'SigSP': 'Sum Shc_p', 'SigAP': 'Sum Gab1_p', 'SigG_O': 'Sum Grb2-SOS', 'SigG_A': 'Sum Grb2-Gab1', 'SigSP_G': 'Sum Shc_p-Grb2', 'SigAP_S': 'Sum Gab1_p-Shc', 'SigAP_I': 'Sum Gab1_p-PI-3K', 'SigAP_R': 'Sum Gab1_p-RasGAP', 'Empty': 'Empty', 'P3_A': 'PIP3-Gab1', 'P2': 'PIP2', 'P3': 'PIP3', 'Akt': 'Akt', 'RsD': 'RasGDP', 'RsT': 'RasGTP', 'SigRP': 'Sum RasGAP_p', 'Raf': 'Raf', 'Rafstar': 'Raf*', 'MEK': 'MEK', 'MEKstar': 'MEK*', 'ERK': 'ERK', 'ERKstar': 'ERK*', 'OP': 'SOS_p', 'AP': 'Gab1_p', 'A_SigG_O': 'Gab1_SumGrb2-SOS', 'SigA_G': 'Sum PIP3-Gab1-Grb2', 'SigA_G_O': 'Sum PIP3-Gab1-Grb2_SOS', 'SigO': 'Sum SOS', 'E13': 'ErbB1-ErbB3', 'E14': 'ErbB1-ErbB4', 'E13P': 'ErbB1-ErbB3_p', 'E14P': 'ErbB1-ErbB3_p', 'E13G': 'E13-Grb2', 'E13S': 'E13-Shc', 'E13I': 'E13-PI-3K', 'E13R': 'E13-RasGAP', 'E14G': 'E14-Grb2', 'E14S': 'E14-Shc', 'E14I': 'E14-PI-3K', 'E14R': 'E14-RasGAP', 'T': 'PTP-1B', 'E11T': 'E11-PTP-1B', 'E12T': 'E12-PTP-1B', 'E23T': 'E23-PTP-1B', 'E34T': 'E34-PTP-1B', 'E24T': 'E24-PTP-1B', 'E44T': 'E44-PTP-1B', 'E13T': 'E13-PTP-1B', 'E14T': 'E14-PTP-1B', 'SigT': 'Sig-PTP-1B', 'E1_PT': 'E1_p-PTP-1B', 'E2_PT': 'E2_p-PTP-1B', 'E4_PT': 'E4_p-PTP-1B', 'E_E1_PT': 'E_E1_p-PTP-1B', 'H_E4_PT': 'H_E4_p-PTP-1B', 'Aktstar': 'Aktstar', 'SigAP_T': 'SumGab1_p-PTP-1B', 'E': 'EGF', 'H': 'HRG', 'fint': 'fint', 'pERK': 'p_ERK', 'ERK_MEKstar': 'ERK-MEK*', 'pERK_MEKstar': 'p_ERK-MEK*', 'pERK_ERKpase': 'p_ERK-ERKpase', 'ERKpase': 'ERKpase', 'ERKstar_ERKpase': 'ERK*-ERKpase', 'norm_Akt_star': 'normalized Akt*', 'norm_Erk_star': 'normalized Erk*'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_model_state_raf': ('Raf', 743.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Raf`.'), 'initial_erb_b4': ('E4', 399.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `E4`.'), 'initial_erb_b3': ('E3', 294.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `E3`.'), 'initial_erb_b1': ('E1', 274.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `E1`.'), 'initial_pip2': ('P2', 197.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `P2`.'), 'initial_erb_b2': ('E2', 158.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `E2`.')}
    _HEADLINE_OUTPUTS = {'raf': ('Raf', 'native SBML value', 'Raf. Maps to SBML symbol `Raf`.'), 'erb_b4': ('E4', 'native SBML value', 'ErbB4. Maps to SBML symbol `E4`.'), 'erb_b3': ('E3', 'native SBML value', 'ErbB3. Maps to SBML symbol `E3`.'), 'erb_b1': ('E1', 'native SBML value', 'ErbB1. Maps to SBML symbol `E1`.'), 'pip2': ('P2', 'native SBML value', 'PIP2. Maps to SBML symbol `P2`.'), 'erb_b2': ('E2', 'native SBML value', 'ErbB2. Maps to SBML symbol `E2`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/BIOMD0000000175.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
