# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Chatterjee2010_BloodCoagulation."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Chatterjee2010BloodcoagulationModel1108260014Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Chatterjee2010_BloodCoagulation."""

    _SBML_ID = 'MODEL1108260014'
    _TITLE = 'Chatterjee2010_BloodCoagulation'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['species_1', 'species_2', 'species_3', 'species_4', 'species_5', 'species_6', 'species_7', 'species_8', 'species_9', 'species_10', 'species_11', 'species_12', 'species_13', 'species_14', 'species_15', 'species_16', 'species_17', 'species_18', 'species_19', 'species_20', 'species_21', 'species_22', 'species_23', 'species_24', 'species_25', 'species_26', 'species_27', 'species_28', 'species_29', 'species_30', 'species_31', 'species_32', 'species_33', 'species_34', 'species_35', 'species_36', 'species_37', 'species_38', 'species_39', 'species_40', 'species_41', 'species_42', 'species_43', 'species_44', 'species_45', 'species_46', 'species_47', 'species_48', 'species_49', 'species_50', 'species_51', 'species_52', 'species_53', 'species_54', 'species_55', 'species_56', 'species_57', 'species_58', 'species_59', 'species_60', 'species_61', 'species_62', 'species_63', 'species_64', 'species_65', 'species_66', 'species_67', 'species_68', 'species_69', 'species_70', 'species_71', 'species_72', 'species_73', 'species_74', 'species_75', 'species_76', 'species_77', 'species_78', 'species_79', 'species_80', 'species_81']
    _SPECIES_LABELS = {'species_1': 'TF', 'species_2': 'TF_VII', 'species_3': 'VII', 'species_4': 'TF_VIIa', 'species_5': 'VIIa', 'species_6': 'Xa', 'species_7': 'IIa', 'species_8': 'TF_VIIa_X', 'species_9': 'X', 'species_10': 'TF_VIIa_Xa', 'species_11': 'IX', 'species_12': 'TF_VIIa_IX', 'species_13': 'IXa', 'species_14': 'II', 'species_15': 'VIII', 'species_16': 'VIIIa', 'species_17': 'IXa_VIIIa', 'species_18': 'IXa_VIIIa_X', 'species_19': 'VIIIa1_L', 'species_20': 'VIIIa2', 'species_21': 'V', 'species_22': 'Va', 'species_23': 'Xa_Va', 'species_24': 'Xa_Va_IIa', 'species_25': 'mIIa', 'species_26': 'TFPI', 'species_27': 'Xa_TFPI', 'species_28': 'TF_VIIa_Xa_TFPI', 'species_29': 'ATIII', 'species_30': 'Xa_ATIII', 'species_31': 'mIIa_ATIII', 'species_32': 'IXa_ATIII', 'species_33': 'IIa_ATIII', 'species_34': 'TF_VIIa_ATIII', 'species_35': 'AMC', 'species_36': 'Boc_VPR_MCA', 'species_37': 'Boc_VPR_MCA_IIa', 'species_38': 'Boc_VPR', 'species_39': 'XII', 'species_40': 'XIIa', 'species_41': 'XIIa_XII', 'species_42': 'PK', 'species_43': 'XIIa_PK', 'species_44': 'K', 'species_45': 'XII_K', 'species_46': 'K.inhibited', 'species_47': 'CTI', 'species_48': 'XIIa_CTI', 'species_49': 'C1inh', 'species_50': 'XIIa_ATIII', 'species_51': 'XI', 'species_52': 'XI_IIa', 'species_53': 'XIa', 'species_54': 'XIIa_XI', 'species_55': 'XIa_C1inh', 'species_56': 'XIa_alpha1AT', 'species_57': 'alpha1AT', 'species_58': 'XIa_alpha2AP', 'species_59': 'alpha2AP', 'species_60': 'XIa_IX', 'species_61': 'IXa_X', 'species_62': 'Xa_VIII', 'species_63': 'VIIa_IX', 'species_64': 'VIIa_X', 'species_65': 'Fbg', 'species_66': 'Fbg_IIa', 'species_67': 'FPA', 'species_68': 'Fbn1', 'species_69': 'Fbn1_IIa', 'species_70': 'FPB', 'species_71': 'Fbn2', 'species_72': 'Fbn1x2', 'species_73': 'Fbn1x2_IIa', 'species_74': 'Fbn2x2', 'species_75': 'Fbn2_IIa', 'species_76': 'Fbn1x2_IIa_ATIII', 'species_77': 'Fbn1_IIa_ATIII', 'species_78': 'Fbn2_IIa_ATIII', 'species_79': 'Xa_Va_II', 'species_80': 'XIIa_C1inh', 'species_81': 'XIa_ATIII'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_alpha1_at': ('species_57', 4.5e-05, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_57`.'), 'initial_boc_vpr_mca': ('species_36', 1e-05, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_36`.'), 'initial_model_state_fbg': ('species_65', 9e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_65`.'), 'initial_model_state_cti': ('species_47', 4.2e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_47`.'), 'initial_atiii': ('species_29', 3.4e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_29`.'), 'initial_c1inh': ('species_49', 2.5e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_49`.')}
    _HEADLINE_OUTPUTS = {'alpha1_at': ('species_57', 'native SBML value', 'alpha1AT. Maps to SBML symbol `species_57`.'), 'boc_vpr_mca': ('species_36', 'native SBML value', 'Boc_VPR_MCA. Maps to SBML symbol `species_36`.'), 'fbg': ('species_65', 'native SBML value', 'Fbg. Maps to SBML symbol `species_65`.'), 'cti': ('species_47', 'native SBML value', 'CTI. Maps to SBML symbol `species_47`.'), 'atiii': ('species_29', 'native SBML value', 'ATIII. Maps to SBML symbol `species_29`.'), 'c1inh': ('species_49', 'native SBML value', 'C1inh. Maps to SBML symbol `species_49`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL1108260014.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
