schema_version: '2.0'
title: Cao2013 Application Of Absis Method In The Reversible Isomerizatio Lab
description: Youfang Cao & Jie Liang. Adaptively biased sequential importance sampling
  for rare events in reaction networks with comparison to exact solutions from finite
  buffer dCME method.
models:
- alias: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.state
  to:
  - visualisation.systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model_state
- from: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.summary
  to:
  - visualisation.systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model_summary
- from: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.species_labels
  to:
  - visualisation.systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model_species_labels
runtime:
  duration: 1.0
  communication_step: 0.1
  initial_inputs: {}
tags:
- systemsbiology
- sbml
- biomodels_ebi
- faithful
- curated
io:
  inputs:
  - name: initial_model_state_b
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.initial_model_state_b
    label: Initial Model State B
    description: Source state initial condition exposed as a model-specific control
      because no explicit intervention parameter is identifiable. Maps to SBML symbol
      `B`.
  - name: initial_model_state_a
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.initial_model_state_a
    label: Initial Model State A
    description: Source state initial condition exposed as a model-specific control
      because no explicit intervention parameter is identifiable. Maps to SBML symbol
      `A`.
  outputs:
  - name: state
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.state
  - name: summary
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.summary
  - name: species_labels
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.species_labels
  - name: model_state_b
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.model_state_b
  - name: model_state_a
    maps_to: systemsbiology_sbml_cao2013_application_of_absis_method_in_the_rever_biomd0000000486_model.model_state_a
