# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Hayer2005_simple_AMPAR_traff_model2."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Hayer2005SimpleAmparTraffModel2Model9086628127Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Hayer2005_simple_AMPAR_traff_model2."""

    _SBML_ID = 'MODEL9086628127'
    _TITLE = 'Hayer2005_simple_AMPAR_traff_model2'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['Membrane_slash_PP1_minus_active', 'Membrane_slash_PP1_minus_active_slash_PP1_slash_PP1_cplx', 'Membrane_slash_PP1_minus_active_slash_PP1_sbo_1_sbc__slash_PP1_sbo_1_sbc__cplx', 'Membrane_slash_MR_star_', 'Membrane_slash_MR', 'Membrane_slash_MR_star__star_', 'Internal_slash_IR_star__star_', 'Internal_slash_IR', 'Internal_slash_IR_star_', 'PKA_minus_active_slash_memb_minus_PKA_minus_act_slash_memb_minus_PKA_minus_act_cplx', 'PKA_minus_active_slash_internal_minus_PKA_minus_act_slash_internal_minus_PKA_minus_act_cplx', 'PKA_minus_active_slash_memb_minus_PKA_minus_act_sbo_1_sbc__slash_memb_minus_PKA_minus_act_sbo_1_sbc__cplx', 'PKA_minus_active_slash_internal_minus_PKA_minus_act_sbo_1_sbc__slash_internal_minus_PKA_minus_act_sbo_1_sbc__cplx', 'Anchor', 'PKA_minus_active', 'Bulk_AMPAR']
    _SPECIES_LABELS = {'Membrane_slash_PP1_minus_active': 'Membrane Slash PP1 Minus Active', 'Membrane_slash_PP1_minus_active_slash_PP1_slash_PP1_cplx': 'Membrane Slash PP1 Minus Active Slash PP1 Slash PP1 Cplx', 'Membrane_slash_PP1_minus_active_slash_PP1_sbo_1_sbc__slash_PP1_sbo_1_sbc__cplx': 'Membrane Slash PP1 Minus Active Slash PP1 Sbo 1 Sbc Slash PP1 Sbo 1 Sbc Cplx', 'Membrane_slash_MR_star_': 'Membrane Slash MR Star', 'Membrane_slash_MR': 'Membrane Slash MR', 'Membrane_slash_MR_star__star_': 'Membrane Slash MR Star Star', 'Internal_slash_IR_star__star_': 'Internal Slash IR Star Star', 'Internal_slash_IR': 'Internal Slash IR', 'Internal_slash_IR_star_': 'Internal Slash IR Star', 'PKA_minus_active_slash_memb_minus_PKA_minus_act_slash_memb_minus_PKA_minus_act_cplx': 'PKA Minus Active Slash Memb Minus PKA Minus Act Slash Memb Minus PKA Minus Act Cplx', 'PKA_minus_active_slash_internal_minus_PKA_minus_act_slash_internal_minus_PKA_minus_act_cplx': 'PKA Minus Active Slash Internal Minus PKA Minus Act Slash Internal Minus PKA Minus Act Cplx', 'PKA_minus_active_slash_memb_minus_PKA_minus_act_sbo_1_sbc__slash_memb_minus_PKA_minus_act_sbo_1_sbc__cplx': 'PKA Minus Active Slash Memb Minus PKA Minus Act Sbo 1 Sbc Slash Memb Minus PKA Minus Act Sbo 1 Sbc Cplx', 'PKA_minus_active_slash_internal_minus_PKA_minus_act_sbo_1_sbc__slash_internal_minus_PKA_minus_act_sbo_1_sbc__cplx': 'PKA Minus Active Slash Internal Minus PKA Minus Act Sbo 1 Sbc Slash Internal Minus PKA Minus Act Sbo 1 Sbc Cplx', 'Anchor': 'Anchor', 'PKA_minus_active': 'PKA Minus Active', 'Bulk_AMPAR': 'Bulk AMPAR'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_internal_slash_ir_star': ('Internal_slash_IR_star_', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Internal_slash_IR_star_`.'), 'initial_internal_slash_ir': ('Internal_slash_IR', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Internal_slash_IR`.'), 'initial_pka_minus_active_slash_internal_minus_pka_minus_act_slash_internal_minus_pka_minus_act_cplx': ('PKA_minus_active_slash_internal_minus_PKA_minus_act_slash_internal_minus_PKA_minus_act_cplx', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `PKA_minus_active_slash_internal_minus_PKA_minus_act_slash_internal_minus_PKA_minus_act_cplx`.'), 'initial_pka_minus_active_slash_internal_minus_pka_minus_act_sbo_1_sbc_slash_internal_minus_pka_minus_act_sbo_1_sbc_cplx': ('PKA_minus_active_slash_internal_minus_PKA_minus_act_sbo_1_sbc__slash_internal_minus_PKA_minus_act_sbo_1_sbc__cplx', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `PKA_minus_active_slash_internal_minus_PKA_minus_act_sbo_1_sbc__slash_internal_minus_PKA_minus_act_sbo_1_sbc__cplx`.'), 'initial_internal_slash_ir_star_star': ('Internal_slash_IR_star__star_', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Internal_slash_IR_star__star_`.'), 'initial_anchor': ('Anchor', 27.3333333333333, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Anchor`.')}
    _HEADLINE_OUTPUTS = {'internal_slash_ir_star': ('Internal_slash_IR_star_', 'native SBML value', 'Internal Slash IR Star. Maps to SBML symbol `Internal_slash_IR_star_`.'), 'internal_slash_ir': ('Internal_slash_IR', 'native SBML value', 'Internal Slash IR. Maps to SBML symbol `Internal_slash_IR`.'), 'pka_minus_active_slash_internal_minus_pka_minus_act_slash_internal_minus_pka_minus_act_cplx': ('PKA_minus_active_slash_internal_minus_PKA_minus_act_slash_internal_minus_PKA_minus_act_cplx', 'native SBML value', 'PKA Minus Active Slash Internal Minus PKA Minus Act Slash Internal Minus PKA Minus Act Cplx. Maps to SBML symbol `PKA_minus_active_slash_internal_minus_PKA_minus_act_slash_internal_minus_PKA_minus_act_cplx`.'), 'pka_minus_active_slash_internal_minus_pka_minus_act_sbo_1_sbc_slash_internal_minus_pka_minus_act_sbo_1_sbc_cplx': ('PKA_minus_active_slash_internal_minus_PKA_minus_act_sbo_1_sbc__slash_internal_minus_PKA_minus_act_sbo_1_sbc__cplx', 'native SBML value', 'PKA Minus Active Slash Internal Minus PKA Minus Act Sbo 1 Sbc Slash Internal Minus PKA Minus Act Sbo 1 Sbc Cplx. Maps to SBML symbol `PKA_minus_active_slash_internal_minus_PKA_minus_act_sbo_1_sbc__slash_internal_minus_PKA_minus_act_sbo_1_sbc__cplx`.'), 'internal_slash_ir_star_star': ('Internal_slash_IR_star__star_', 'native SBML value', 'Internal Slash IR Star Star. Maps to SBML symbol `Internal_slash_IR_star__star_`.'), 'anchor': ('Anchor', 'native SBML value', 'Anchor. Maps to SBML symbol `Anchor`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL9086628127.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
