# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Jenkinson2011_EGF_MAPK."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Jenkinson2011EgfMapkBiomd0000000399Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Jenkinson2011_EGF_MAPK."""

    _SBML_ID = 'BIOMD0000000399'
    _TITLE = 'Jenkinson2011_EGF_MAPK'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31', 'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39', 'x40', 'x41', 'x42', 'x43', 'x44', 'x45', 'x46', 'x47', 'x48', 'x49', 'x50', 'x51', 'x52', 'x53', 'x54', 'x55', 'x56', 'x57', 'x58', 'x59', 'x60', 'x61', 'x62', 'x63', 'x64', 'x65', 'x66', 'x67', 'x68', 'x69', 'x70', 'x71', 'x72', 'x73', 'x74', 'x75', 'x76', 'x77', 'x78', 'x79', 'x80', 'x81', 'x82', 'x83', 'x84', 'x85', 'x86', 'x87', 'x88', 'x89', 'x90', 'x91', 'x92', 'x93', 'x94', 'Raf_act', 'Ras_GTP', 'MEK_PP', 'ERK_PP', 'SHC_P_t', 'EGF_EGFR_act']
    _SPECIES_LABELS = {'x1': 'EGF', 'x2': 'EGFR', 'x3': 'EGF-EGFR', 'x4': 'EGF-EGFR^2', 'x5': 'EGF-EGFR*^2', 'x6': 'EGFRi', 'x7': 'EGF-EGFR*^2-GAP-Grb2-Prot', 'x8': 'EGF-EGFRi*^2', 'x9': 'Proti', 'x10': 'EGF-EGFRi', 'x11': 'EGF-EGFRi^2', 'x12': 'Prot', 'x13': 'EGFideg', 'x14': 'GAP', 'x15': 'EGF-EGFR*^2-GAP', 'x16': 'EGFi', 'x17': 'EGF-EGFRi*^2-GAP', 'x18': 'EGF-EGFRi*^2-GAP-Grb2', 'x19': 'EGF-EGFRi*^2-GAP-Grb2-Sos', 'x20': 'EGF-EGFRi*^2-GAP-Grb2-Sos-Ras-GDP', 'x21': 'EGF-EGFRi*^2-GAP-Grb2-Sos-Ras-GTP', 'x22': 'Grb2', 'x23': 'EGF-EGFR*^2-GAP-Grb2', 'x24': 'Sos', 'x25': 'EGF-EGFR*^2-GAP-Grb2-Sos', 'x26': 'Ras-GDP', 'x27': 'EGF-EGFR*^2-GAP-Grb2-Sos-Ras-GDP', 'x28': 'Ras-GTP', 'x29': 'EGF-EGFR*^2-GAP-Grb2-Sos-Ras-GTP', 'x30': 'Grb2-Sos', 'x31': 'Shc', 'x32': 'EGF-EGFR*^2-GAP-Shc', 'x33': 'EGF-EGFR*^2-GAP-Shc*', 'x34': 'EGF-EGFR*^2-GAP-Shc*-Grb2', 'x35': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Sos', 'x36': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Sos-Ras-GDP', 'x37': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Sos-Ras-GTP', 'x38': 'Shc*-Grb2-Sos', 'x39': 'Shc*-Grb2', 'x40': 'Shc*', 'x41': 'Raf', 'x42': 'Raf-Ras-GTP', 'x43': 'Ras-GTP*', 'x44': 'Phosphotase1', 'x45': 'Raf*', 'x46': "Raf*-P'ase", 'x47': 'MEK', 'x48': 'MEK-Raf*', 'x49': 'MEK-P', 'x50': 'MEK-P-Raf*', 'x51': 'MEK-PP', 'x52': "MEK-PP-P'ase2", 'x53': 'Phosphatase2', 'x54': "MEK-P-P'ase2", 'x55': 'ERK', 'x56': 'ERK-MEK-PP', 'x57': 'ERK-P', 'x58': 'ERK-P-MEK-PP', 'x59': 'ERK-PP', 'x60': 'Phosphotase3', 'x61': "ERK-PP-P'ase3", 'x62': "ERK-P-P'ase3", 'x63': 'EGF-EGFRi*^2-GAP-Shc', 'x64': 'EGF-EGFRi*^2-GAP-Shc*', 'x65': 'EGF-EGFRi*^2-GAP-Shc*-Grb2', 'x66': 'EGF-EGFRi*^2-GAP-Shc*-Grb2-Sos', 'x67': 'EGF-EGFRi*^2-GAP-Shc*-Grb2-Sos-Ras-GDP', 'x68': 'EGF-EGFRi*^2-GAP-Shc*-Grb2-Sos-Ras-GTP', 'x69': 'Rasi-GTP', 'x70': 'Rafi-Rasi-GTP', 'x71': 'Rasi-GTP*', 'x72': 'Rafi*', 'x73': "Rafi*-P'ase", 'x74': 'MEKi-Rafi*', 'x75': 'MEKi-P', 'x76': 'MEKi-P-Rafi*', 'x77': 'MEKi-PP', 'x78': "MEKi-PP-P'ase2i", 'x79': "MEKi-P-P'ase2i", 'x80': 'ERKi-MEKi-PP', 'x81': 'ERKi-P', 'x82': 'ERKi-P-MEKi-PP', 'x83': 'ERKi-PP', 'x84': "ERKi-PP-P'ase3i", 'x85': "ERKi-P-P'ase3i", 'x86': 'EGFRideg', 'x87': 'EGF-EGFRi*^2deg', 'x88': 'EGF-EGFR*^2-GAP-Grb2-Sos-Prot', 'x89': 'EGF-EGFR*^2-GAP-Grb2-Sos-Ras-GDP-Prot', 'x90': 'EGF-EGFR*^2-GAP-Grb2-Sos-Ras-GTP-Prot', 'x91': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Prot', 'x92': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Sos-Prot', 'x93': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Sos-Ras-GDP-Prot', 'x94': 'EGF-EGFR*^2-GAP-Shc*-Grb2-Sos-Ras-GTP-Prot', 'Raf_act': 't_Raf*', 'Ras_GTP': 't_Ras_GTP', 'MEK_PP': 't_MEK_PP', 'ERK_PP': 't_ERK_PP', 'SHC_P_t': 't_SHC_P_t', 'EGF_EGFR_act': 't_EGF_EGFR*'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_model_state_mek': ('x47', 22000000.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `x47`.'), 'initial_model_state_erk': ('x55', 21000000.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `x55`.'), 'initial_phosphotase3': ('x60', 10000000.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `x60`.'), 'initial_model_state_shc': ('x31', 101000.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `x31`.'), 'initial_prot': ('x12', 81000.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `x12`.'), 'initial_ras_gdp': ('x26', 72000.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `x26`.')}
    _HEADLINE_OUTPUTS = {'mek': ('x47', 'native SBML value', 'MEK. Maps to SBML symbol `x47`.'), 'erk': ('x55', 'native SBML value', 'ERK. Maps to SBML symbol `x55`.'), 'phosphotase3': ('x60', 'native SBML value', 'Phosphotase3. Maps to SBML symbol `x60`.'), 'shc': ('x31', 'native SBML value', 'Shc. Maps to SBML symbol `x31`.'), 'prot': ('x12', 'native SBML value', 'Prot. Maps to SBML symbol `x12`.'), 'ras_gdp': ('x26', 'native SBML value', 'Ras-GDP. Maps to SBML symbol `x26`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/BIOMD0000000399.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
