# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Verma2016 - Ca(2+) Signal Propagation Along Hepatocyte Cords."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Verma2016Ca2SignalPropagationAlongHepatocyBiomd0000000834Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Verma2016 - Ca(2+) Signal Propagation Along Hepatocyte Cords."""

    _SBML_ID = 'BIOMD0000000834'
    _TITLE = 'Verma2016 - Ca(2+) Signal Propagation Along Hepatocyte Cords'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['CaI_1', 'g_1', 'IP3_1', 'r_1', 'CaT_1', 'g_2', 'r_2', 'CaI_2', 'IP3_2', 'CaT_2', 'CaI_3', 'IP3_3', 'g_3', 'r_3', 'CaT_3', 'CaI_4', 'IP3_4', 'r_4', 'g_4', 'CaT_4', 'r_5', 'IP3_5', 'g_5', 'CaI_5', 'CaT_5', 'CaI_6', 'g_6', 'r_6', 'IP3_6', 'CaT_6', 'CaI_7', 'g_7', 'r_7', 'IP3_7', 'CaT_7', 'r_8', 'IP3_8', 'g_8', 'CaI_8', 'CaT_8', 'IP3_9', 'CaI_9', 'r_9', 'g_9', 'CaT_9', 'r_10', 'IP3_10', 'g_10', 'CaI_10', 'CaT_10', 'IP3_11', 'g_11', 'CaI_11', 'r_11', 'IP3_12', 'g_12', 'CaI_12', 'r_12', 'IP3_13', 'g_13', 'CaI_13', 'r_13', 'IP3_14', 'g_14', 'CaI_14', 'r_14', 'IP3_15', 'g_15', 'CaI_15', 'r_15', 'CaT_11', 'CaT_12', 'CaT_13', 'CaT_14', 'CaT_15']
    _SPECIES_LABELS = {'CaI_1': 'cytosolic Ca2+_CaI_1', 'g_1': 'total IP3R_g_1', 'IP3_1': 'cytosolic IP3_IP3_1', 'r_1': 'total receptor levels _r_1', 'CaT_1': 'total intracellular store Ca2+ content_CaT_1', 'g_2': 'total IP3R_g_2', 'r_2': 'total receptor levels _r_2', 'CaI_2': 'cytosolic Ca2+_CaI_2', 'IP3_2': 'cytosolic IP3_IP3_2', 'CaT_2': 'total intracellular store Ca2+ content_CaT_2', 'CaI_3': 'cytosolic Ca2+_CaI_3', 'IP3_3': 'cytosolic IP3_IP3_3', 'g_3': 'total IP3R_g_3', 'r_3': 'total receptor levels _r_3', 'CaT_3': 'total intracellular store Ca2+ content_CaT_3', 'CaI_4': 'cytosolic Ca2+_CaI_4', 'IP3_4': 'cytosolic IP3_IP3_4', 'r_4': 'total receptor levels _r_4', 'g_4': 'total IP3R_g_4', 'CaT_4': 'total intracellular store Ca2+ content_CaT_4', 'r_5': 'total receptor levels _r_5', 'IP3_5': 'cytosolic IP3_IP3_5', 'g_5': 'total IP3R_g_5', 'CaI_5': 'cytosolic Ca2+_CaI_5', 'CaT_5': 'total intracellular store Ca2+ content_CaT_5', 'CaI_6': 'cytosolic Ca2+_CaI_6', 'g_6': 'total IP3R_g_6', 'r_6': 'total receptor levels _r_6', 'IP3_6': 'cytosolic IP3_IP3_6', 'CaT_6': 'total intracellular store Ca2+ content_CaT_6', 'CaI_7': 'cytosolic Ca2+_CaI_7', 'g_7': 'total IP3R_g_7', 'r_7': 'total receptor levels_ r_7', 'IP3_7': 'cytosolic IP3_IP3_7', 'CaT_7': 'total intracellular store Ca2+ content_CaT_7', 'r_8': 'total receptor levels _r_8', 'IP3_8': 'cytosolic IP3_IP3_8', 'g_8': 'total IP3R_g_8', 'CaI_8': 'cytosolic Ca2+_CaI_8', 'CaT_8': 'total intracellular store Ca2+ content_CaT_8', 'IP3_9': 'cytosolic IP3_IP3_9', 'CaI_9': 'cytosolic Ca2+_CaI_9', 'r_9': 'total receptor levels _r_9', 'g_9': 'total IP3R_g_9', 'CaT_9': 'total intracellular store Ca2+ content_CaT_9', 'r_10': 'total receptor levels _r_10', 'IP3_10': 'cytosolic IP3_IP3_10', 'g_10': 'total IP3R_g_10', 'CaI_10': 'cytosolic Ca2+_CaI_10', 'CaT_10': 'total intracellular store Ca2+ content_CaT_10', 'IP3_11': 'cytosolic IP3_IP3_11', 'g_11': 'total IP3R_g_11', 'CaI_11': 'cytosolic Ca2+_CaI_11', 'r_11': 'total receptor levels _r_11', 'IP3_12': 'cytosolic IP3_IP3_12', 'g_12': 'total IP3R_g_12', 'CaI_12': 'cytosolic Ca2+_CaI_12', 'r_12': 'total receptor levels _r_12', 'IP3_13': 'cytosolic IP3_IP3_13', 'g_13': 'total IP3R_g_13', 'CaI_13': 'cytosolic Ca2+_CaI_13', 'r_13': 'total receptor levels _r_13', 'IP3_14': 'cytosolic IP3_IP3_14', 'g_14': 'total IP3R_g_14', 'CaI_14': 'cytosolic Ca2+_CaI_14', 'r_14': 'total receptor levels _r_14', 'IP3_15': 'cytosolic IP3_IP3_15', 'g_15': 'total IP3R_g_15', 'CaI_15': 'cytosolic Ca2+_CaI_15', 'r_15': 'total receptor levels _r_15', 'CaT_11': 'total intracellular store Ca2+ content_CaT_11', 'CaT_12': 'total intracellular store Ca2+ content_CaT_12', 'CaT_13': 'total intracellular store Ca2+ content_CaT_13', 'CaT_14': 'total intracellular store Ca2+ content_CaT_14', 'CaT_15': 'total intracellular store Ca2+ content_CaT_15'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_total_intracellular_store_ca2_content_ca_t_9': ('CaT_9', 500.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CaT_9`.'), 'initial_total_intracellular_store_ca2_content_ca_t_8': ('CaT_8', 500.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CaT_8`.'), 'initial_total_intracellular_store_ca2_content_ca_t_7': ('CaT_7', 500.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CaT_7`.'), 'initial_total_intracellular_store_ca2_content_ca_t_6': ('CaT_6', 500.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CaT_6`.'), 'initial_total_intracellular_store_ca2_content_ca_t_5': ('CaT_5', 500.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CaT_5`.'), 'initial_total_intracellular_store_ca2_content_ca_t_4': ('CaT_4', 500.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `CaT_4`.')}
    _HEADLINE_OUTPUTS = {'total_intracellular_store_ca2_content_ca_t_9': ('CaT_9', 'native SBML value', 'total intracellular store Ca2+ content_CaT_9. Maps to SBML symbol `CaT_9`.'), 'total_intracellular_store_ca2_content_ca_t_8': ('CaT_8', 'native SBML value', 'total intracellular store Ca2+ content_CaT_8. Maps to SBML symbol `CaT_8`.'), 'total_intracellular_store_ca2_content_ca_t_7': ('CaT_7', 'native SBML value', 'total intracellular store Ca2+ content_CaT_7. Maps to SBML symbol `CaT_7`.'), 'total_intracellular_store_ca2_content_ca_t_6': ('CaT_6', 'native SBML value', 'total intracellular store Ca2+ content_CaT_6. Maps to SBML symbol `CaT_6`.'), 'total_intracellular_store_ca2_content_ca_t_5': ('CaT_5', 'native SBML value', 'total intracellular store Ca2+ content_CaT_5. Maps to SBML symbol `CaT_5`.'), 'total_intracellular_store_ca2_content_ca_t_4': ('CaT_4', 'native SBML value', 'total intracellular store Ca2+ content_CaT_4. Maps to SBML symbol `CaT_4`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/BIOMD0000000834.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
