# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Stefan2008 - calmodulin allostery."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Stefan2008CalmodulinAllosteryBiomd0000000183Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Stefan2008 - calmodulin allostery."""

    _SBML_ID = 'BIOMD0000000183'
    _TITLE = 'Stefan2008 - calmodulin allostery'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['species_0', 'species_1', 'species_2', 'species_3', 'species_4', 'species_5', 'species_6', 'species_7', 'species_8', 'species_9', 'species_10', 'species_11', 'species_12', 'species_13', 'species_14', 'species_15', 'species_16', 'species_17', 'species_18', 'species_19', 'species_20', 'species_21', 'species_22', 'species_23', 'species_24', 'species_25', 'species_26', 'species_27', 'species_28', 'species_29', 'species_30', 'species_31', 'species_32', 'species_33', 'species_34', 'species_35', 'species_36', 'species_37', 'species_38', 'species_39', 'species_40', 'species_41', 'species_42', 'species_43', 'species_44', 'species_45', 'species_46', 'species_47', 'species_48', 'species_49', 'species_50', 'species_51', 'species_52', 'species_53', 'species_54', 'species_55', 'species_56', 'species_57', 'species_58', 'species_59', 'species_60', 'species_61', 'species_62', 'species_63', 'species_64', 'species_65', 'species_66']
    _SPECIES_LABELS = {'species_0': 'camR', 'species_1': 'ca', 'species_2': 'camR_ca1_A', 'species_3': 'camR_ca1_B', 'species_4': 'camR_ca1_C', 'species_5': 'camR_ca1_D', 'species_6': 'camR_ca2_AB', 'species_7': 'camR_ca2_AC', 'species_8': 'camR_ca2_AD', 'species_9': 'camR_ca2_BC', 'species_10': 'camR_ca2_BD', 'species_11': 'camR_ca2_CD', 'species_12': 'camR_ca3_ABC', 'species_13': 'camR_ca3_ABD', 'species_14': 'camR_ca3_ACD', 'species_15': 'camR_ca3_BCD', 'species_16': 'camR_ca4_ABCD', 'species_17': 'camT', 'species_18': 'camT_ca1_A', 'species_19': 'camT_ca1_B', 'species_20': 'camT_ca1_C', 'species_21': 'camT_ca1_D', 'species_22': 'camT_ca2_AB', 'species_23': 'camT_ca2_AC', 'species_24': 'camT_ca2_AD', 'species_25': 'camT_ca2_BC', 'species_26': 'camT_ca2_BD', 'species_27': 'camT_ca2_CD', 'species_28': 'camT_ca3_ABC', 'species_29': 'camT_ca3_ABD', 'species_30': 'camT_ca3_ACD', 'species_31': 'camT_ca3_BCD', 'species_32': 'camT_ca4_ABCD', 'species_33': 'CaMKII', 'species_34': 'camR_CaMKII', 'species_35': 'camR_ca1_A_CaMKII', 'species_36': 'camR_ca1_B_CaMKII', 'species_37': 'camR_ca1_C_CaMKII', 'species_38': 'camR_ca1_D_CaMKII', 'species_39': 'camR_ca2_AB_CaMKII', 'species_40': 'camR_ca2_AC_CaMKII', 'species_41': 'camR_ca2_AD_CaMKII', 'species_42': 'camR_ca2_BC_CaMKII', 'species_43': 'camR_ca2_BD_CaMKII', 'species_44': 'camR_ca2_CD_CaMKII', 'species_45': 'camR_ca3_ABC_CaMKII', 'species_46': 'camR_ca3_ABD_CaMKII', 'species_47': 'camR_ca3_ACD_CaMKII', 'species_48': 'camR_ca3_BCD_CaMKII', 'species_49': 'camR_ca4_ABCD_CaMKII', 'species_50': 'PP2B', 'species_51': 'camR_PP2B', 'species_52': 'camR_ca1_A_PP2B', 'species_53': 'camR_ca1_B_PP2B', 'species_54': 'camR_ca1_C_PP2B', 'species_55': 'camR_ca1_D_PP2B', 'species_56': 'camR_ca2_AB_PP2B', 'species_57': 'camR_ca2_AC_PP2B', 'species_58': 'camR_ca2_AD_PP2B', 'species_59': 'camR_ca2_BC_PP2B', 'species_60': 'camR_ca2_BD_PP2B', 'species_61': 'camR_ca2_CD_PP2B', 'species_62': 'camR_ca3_ABC_PP2B', 'species_63': 'camR_ca3_ABD_PP2B', 'species_64': 'camR_ca3_ACD_PP2B', 'species_65': 'camR_ca3_BCD_PP2B', 'species_66': 'camR_ca4_ABCD_PP2B'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_ca_mkii': ('species_33', 7e-05, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_33`.'), 'initial_model_state_ca': ('species_1', 1e-05, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_1`.'), 'initial_pp2_b': ('species_50', 1.6e-06, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_50`.'), 'initial_cam_t': ('species_17', 2e-07, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_17`.'), 'initial_cam_r': ('species_0', 9.7e-12, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_0`.'), 'initial_cam_t_ca4_abcd': ('species_32', 0.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `species_32`.')}
    _HEADLINE_OUTPUTS = {'ca_mkii': ('species_33', 'substance', 'CaMKII. Maps to SBML symbol `species_33`.'), 'model_state_ca': ('species_1', 'substance', 'ca. Maps to SBML symbol `species_1`.'), 'pp2_b': ('species_50', 'substance', 'PP2B. Maps to SBML symbol `species_50`.'), 'cam_t': ('species_17', 'substance', 'camT. Maps to SBML symbol `species_17`.'), 'cam_r': ('species_0', 'substance', 'camR. Maps to SBML symbol `species_0`.'), 'cam_t_ca4_abcd': ('species_32', 'substance', 'camT_ca4_ABCD. Maps to SBML symbol `species_32`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/BIOMD0000000183.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
