# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Luan2007 - Blood coagulation model combining previous models and platelet activation."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Luan2007BloodCoagulationModelCombiningPreviModel1806050001Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Luan2007 - Blood coagulation model combining previous models and platelet activation."""

    _SBML_ID = 'MODEL1806050001'
    _TITLE = 'Luan2007 - Blood coagulation model combining previous models and platelet activation'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['TF', 'VII', 'VII_TF', 'VIIa', 'VIIa_TF', 'Xa', 'Xa_VII_TF', 'IIa', 'IIa_VII_TF', 'X', 'X_VIIa_TF', 'X_VII_TF', 'IX', 'IX_VIIa_TF', 'IX_VII_TF', 'IXa', 'VII_Xa', 'VII_IIa', 'V', 'V_IIa', 'VIII', 'VIII_IIa', 'VIIIa', 'Xa_IX', 'Xa_V', 'Va', 'Xa_VIII', 'II', 'Xa_II', 'IX_P9s', 'P9s', 'IXa_P9s', 'IXa_P9s_0', 'P9s_0', 'P10s', 'X_P10s', 'Xa_P10s', 'P5s', 'V_P5s', 'Va_P5s', 'P8s', 'VIII_P8s', 'VIIIa_P8s', 'II_P2s', 'P2s', 'IIa_P2s', 'AP_Psub', 'PL', 'Psub', 'PL_Psub', 'AP', 'PL_AP', 'PL_AP_Psub', 'PL_IIa', 'PL_Psub_IIa', 'V_P5s_Xa_P10s', 'V_P5s_IIa_P2s', 'IIa_P10s', 'V_P5s_IIa_P10s', 'X_P10s_VIIIa_P8s_IXa_P9s', 'VIIIa_P8s_IXa_P9s', 'VIIIa_P8s_IXa_P9s_0', 'X_P10s_VIIIa_P8s_IXa_P9s_0', 'VIII_P8s_Xa_P10s', 'VIII_P8s_IIa_P2s', 'VIII_P8s_IIa_P10s', 'II_P2s_Va_P5s_Xa_P10s', 'Va_P5s_Xa_P10s', 'Xa_P10s_IX_P9s', 'APC', 'APC_VIIIa_P8s', 'VIIIa_P8s_i', 'APC_Va_P8s', 'Va_P8s', 'Va_P8s_i', 'APC_Va_P5s_Xa_P10s', 'Va_P5s_Xa_P10s_i', 'APC_VIIIa_P8s_IXa_P9s', 'VIIIa_P8s_IXa_P9s_i', 'APC_VIIIa_P8s_IXa_P9s_0', 'VIIIa_P8s_IXa_P9s__i', 'TFPI', 'TFPI_Xa', 'TFPI_Xa_VIIa_TF', 'Xa_VIIa_TF', 'IIa_i', 'ATIII', 'ATIII_IXa', 'IXa_i', 'ATIII_Xa', 'Xa_i', 'ATIII_IIa', 'VIIa_TF_ATIII', 'PC', 'PC_IIa', 'IIa_TM', 'TM', 'IIa_TM_PC']
    _SPECIES_LABELS = {'TF': 'TF', 'VII': 'VII', 'VII_TF': 'VII-TF', 'VIIa': 'VIIa', 'VIIa_TF': 'VIIa-TF', 'Xa': 'Xa', 'Xa_VII_TF': 'Xa-VII-TF', 'IIa': 'IIa', 'IIa_VII_TF': 'IIa-VII-TF', 'X': 'X', 'X_VIIa_TF': 'X-VIIa-TF', 'X_VII_TF': 'X-VII-TF', 'IX': 'IX', 'IX_VIIa_TF': 'IX-VIIa-TF', 'IX_VII_TF': 'IX-VII-TF', 'IXa': 'IXa', 'VII_Xa': 'VII-Xa', 'VII_IIa': 'VII-IIa', 'V': 'V', 'V_IIa': 'V-IIa', 'VIII': 'VIII', 'VIII_IIa': 'VIII-IIa', 'VIIIa': 'VIIIa', 'Xa_IX': 'Xa-IX', 'Xa_V': 'Xa-V', 'Va': 'Va', 'Xa_VIII': 'Xa-VIII', 'II': 'II', 'Xa_II': 'Xa-II', 'IX_P9s': 'IX-P9s', 'P9s': 'P9s', 'IXa_P9s': 'IXa-P9s', 'IXa_P9s_0': 'IXa-P9s*', 'P9s_0': 'P9s*', 'P10s': 'P10s', 'X_P10s': 'X-P10s', 'Xa_P10s': 'Xa-P10s', 'P5s': 'P5s', 'V_P5s': 'V-P5s', 'Va_P5s': 'Va-P5s', 'P8s': 'P8s', 'VIII_P8s': 'VIII-P8s', 'VIIIa_P8s': 'VIIIa-P8s', 'II_P2s': 'II-P2s', 'P2s': 'P2s', 'IIa_P2s': 'IIa-P2s', 'AP_Psub': 'AP-Psub', 'PL': 'PL', 'Psub': 'Psub', 'PL_Psub': 'PL-Psub', 'AP': 'AP', 'PL_AP': 'PL-AP', 'PL_AP_Psub': 'PL-AP-Psub', 'PL_IIa': 'PL-IIa', 'PL_Psub_IIa': 'PL-Psub-IIa', 'V_P5s_Xa_P10s': 'V-P5s-Xa-P10s', 'V_P5s_IIa_P2s': 'V-P5s-IIa-P2s', 'IIa_P10s': 'IIa-P10s', 'V_P5s_IIa_P10s': 'V-P5s-IIa-P10s', 'X_P10s_VIIIa_P8s_IXa_P9s': 'X-P10s-VIIIa-P8s-IXa-P9s', 'VIIIa_P8s_IXa_P9s': 'VIIIa-P8s-IXa-P9s', 'VIIIa_P8s_IXa_P9s_0': 'VIIIa-P8s-IXa-P9s*', 'X_P10s_VIIIa_P8s_IXa_P9s_0': 'X-P10s-VIIIa-P8s-IXa-P9s*', 'VIII_P8s_Xa_P10s': 'VIII-P8s-Xa-P10s', 'VIII_P8s_IIa_P2s': 'VIII-P8s-IIa-P2s', 'VIII_P8s_IIa_P10s': 'VIII-P8s-IIa-P10s', 'II_P2s_Va_P5s_Xa_P10s': 'II-P2s-Va-P5s-Xa-P10s', 'Va_P5s_Xa_P10s': 'Va-P5s-Xa-P10s', 'Xa_P10s_IX_P9s': 'Xa-P10s-IX-P9s', 'APC': 'APC', 'APC_VIIIa_P8s': 'APC-VIIIa-P8s', 'VIIIa_P8s_i': 'VIIIa-P8s-i', 'APC_Va_P8s': 'APC-Va-P8s', 'Va_P8s': 'Va-P8s', 'Va_P8s_i': 'Va-P8s-i', 'APC_Va_P5s_Xa_P10s': 'APC-Va-P5s-Xa-P10s', 'Va_P5s_Xa_P10s_i': 'Va-P5s-Xa-P10s-i', 'APC_VIIIa_P8s_IXa_P9s': 'APC-VIIIa-P8s-IXa-P9s', 'VIIIa_P8s_IXa_P9s_i': 'VIIIa-P8s-IXa-P9s-i', 'APC_VIIIa_P8s_IXa_P9s_0': 'APC-VIIIa-P8s-IXa-P9s*', 'VIIIa_P8s_IXa_P9s__i': 'VIIIa-P8s-IXa-P9s*-i', 'TFPI': 'TFPI', 'TFPI_Xa': 'TFPI-Xa', 'TFPI_Xa_VIIa_TF': 'TFPI-Xa-VIIa-TF', 'Xa_VIIa_TF': 'Xa-VIIa-TF', 'IIa_i': 'IIa-i', 'ATIII': 'ATIII', 'ATIII_IXa': 'ATIII-IXa', 'IXa_i': 'IXa-i', 'ATIII_Xa': 'ATIII-Xa', 'Xa_i': 'Xa-i', 'ATIII_IIa': 'ATIII-IIa', 'VIIa_TF_ATIII': 'VIIa-TF-ATIII', 'PC': 'PC', 'PC_IIa': 'PC-IIa', 'IIa_TM': 'IIa-TM', 'TM': 'TM', 'IIa_TM_PC': 'IIa-TM-PC'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_model_state_p5s': ('P5s', 50.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `P5s`.'), 'initial_model_state_p2s': ('P2s', 0.5, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `P2s`.'), 'initial_model_state_p8s': ('P8s', 5e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `P8s`.'), 'initial_model_state_p9s': ('P9s_0', 5e-08, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `P9s_0`.'), 'initial_model_state_p9s_2': ('P9s', 5e-08, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `P9s`.'), 'initial_xa_i': ('Xa_i', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Xa_i`.')}
    _HEADLINE_OUTPUTS = {'p5s': ('P5s', 'native SBML value', 'P5s. Maps to SBML symbol `P5s`.'), 'p2s': ('P2s', 'native SBML value', 'P2s. Maps to SBML symbol `P2s`.'), 'p8s': ('P8s', 'native SBML value', 'P8s. Maps to SBML symbol `P8s`.'), 'p9s': ('P9s_0', 'native SBML value', 'P9s*. Maps to SBML symbol `P9s_0`.'), 'p9s_2': ('P9s', 'native SBML value', 'P9s. Maps to SBML symbol `P9s`.'), 'xa_i': ('Xa_i', 'native SBML value', 'Xa-i. Maps to SBML symbol `Xa_i`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL1806050001.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
