# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Sarai2003_CardiacSAnodePacemaker."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Sarai2003CardiacsanodepacemakerModel1006230108Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Sarai2003_CardiacSAnodePacemaker."""

    _SBML_ID = 'MODEL1006230108'
    _TITLE = 'Sarai2003_CardiacSAnodePacemaker'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'rate_rules'
    _OBSERVABLES = ['Vm_membrane', 'Nai', 'Ki', 'Ca_Total_internal_ion_concentrations', 'ATPi', 'p_RP_Na', 'p_AP_Na', 'p_AI_Na', 'y_sodium_current_ultra_slow_gate', 'p_RP_CaL', 'p_AP_CaL', 'p_AI_CaL', 'p_U', 'p_UCa', 'p_C', 'y_L_type_Ca_channel_ultra_slow_gate', 'y1_T_type_Ca_channel_y1_gate', 'y2_T_type_Ca_channel_y2_gate', 'y1_st_channel_y1_gate', 'y2_st_channel_y2_gate', 'y3_st_channel_y3_gate', 'O1', 'O2', 'C1', 'C2', 'y_time_independent_potassium_current_y_gate', 'y1_rapid_time_dependent_potassium_current_y1_gate', 'y2_rapid_time_dependent_potassium_current_y2_gate', 'y3_rapid_time_dependent_potassium_current_y3_gate', 'y_ACh_dependent_potassium_current_y_gate', 'y_sodium_calcium_exchanger_y_gate', 'y_sodium_potassium_pump_y_gate', 'y_SR_calcium_pump_y_gate', 'p_open_RyR', 'p_close_RyR', 'Ca_Total_Ca_concentrations_in_SR', 'Caup', 'pCa', 'pCaCB', 'pCB', 'X']
    _SPECIES_LABELS = {'Vm_membrane': 'Vm Membrane', 'Nai': 'Nai', 'Ki': 'Ki', 'Ca_Total_internal_ion_concentrations': 'Ca Total Internal Ion Concentrations', 'ATPi': 'ATPi', 'p_RP_Na': 'P RP Na', 'p_AP_Na': 'P AP Na', 'p_AI_Na': 'P AI Na', 'y_sodium_current_ultra_slow_gate': 'Y Sodium Current Ultra Slow Gate', 'p_RP_CaL': 'P RP CaL', 'p_AP_CaL': 'P AP CaL', 'p_AI_CaL': 'P AI CaL', 'p_U': 'P U', 'p_UCa': 'P UCa', 'p_C': 'P C', 'y_L_type_Ca_channel_ultra_slow_gate': 'Y L Type Ca Channel Ultra Slow Gate', 'y1_T_type_Ca_channel_y1_gate': 'Y1 T Type Ca Channel Y1 Gate', 'y2_T_type_Ca_channel_y2_gate': 'Y2 T Type Ca Channel Y2 Gate', 'y1_st_channel_y1_gate': 'Y1 St Channel Y1 Gate', 'y2_st_channel_y2_gate': 'Y2 St Channel Y2 Gate', 'y3_st_channel_y3_gate': 'Y3 St Channel Y3 Gate', 'O1': 'O1', 'O2': 'O2', 'C1': 'C1', 'C2': 'C2', 'y_time_independent_potassium_current_y_gate': 'Y Time Independent Potassium Current Y Gate', 'y1_rapid_time_dependent_potassium_current_y1_gate': 'Y1 Rapid Time Dependent Potassium Current Y1 Gate', 'y2_rapid_time_dependent_potassium_current_y2_gate': 'Y2 Rapid Time Dependent Potassium Current Y2 Gate', 'y3_rapid_time_dependent_potassium_current_y3_gate': 'Y3 Rapid Time Dependent Potassium Current Y3 Gate', 'y_ACh_dependent_potassium_current_y_gate': 'Y ACh Dependent Potassium Current Y Gate', 'y_sodium_calcium_exchanger_y_gate': 'Y Sodium Calcium Exchanger Y Gate', 'y_sodium_potassium_pump_y_gate': 'Y Sodium Potassium Pump Y Gate', 'y_SR_calcium_pump_y_gate': 'Y SR Calcium Pump Y Gate', 'p_open_RyR': 'P Open RyR', 'p_close_RyR': 'P Close RyR', 'Ca_Total_Ca_concentrations_in_SR': 'Ca Total Ca Concentrations In SR', 'Caup': 'Caup', 'pCa': 'PCa', 'pCaCB': 'PCaCB', 'pCB': 'PCB', 'X': 'X'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_at_pi': ('ATPi', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `ATPi`.'), 'initial_ca_total_internal_ion_concentrations': ('Ca_Total_internal_ion_concentrations', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Ca_Total_internal_ion_concentrations`.'), 'initial_y3_st_channel_y3_gate': ('y3_st_channel_y3_gate', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `y3_st_channel_y3_gate`.'), 'initial_y2_st_channel_y2_gate': ('y2_st_channel_y2_gate', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `y2_st_channel_y2_gate`.'), 'initial_y1_st_channel_y1_gate': ('y1_st_channel_y1_gate', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `y1_st_channel_y1_gate`.'), 'initial_y_sr_calcium_pump_y_gate': ('y_SR_calcium_pump_y_gate', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `y_SR_calcium_pump_y_gate`.')}
    _HEADLINE_OUTPUTS = {'at_pi': ('ATPi', 'native SBML value', 'ATPi. Maps to SBML symbol `ATPi`.'), 'ca_total_internal_ion_concentrations': ('Ca_Total_internal_ion_concentrations', 'native SBML value', 'Ca Total Internal Ion Concentrations. Maps to SBML symbol `Ca_Total_internal_ion_concentrations`.'), 'y3_st_channel_y3_gate': ('y3_st_channel_y3_gate', 'native SBML value', 'Y3 St Channel Y3 Gate. Maps to SBML symbol `y3_st_channel_y3_gate`.'), 'y2_st_channel_y2_gate': ('y2_st_channel_y2_gate', 'native SBML value', 'Y2 St Channel Y2 Gate. Maps to SBML symbol `y2_st_channel_y2_gate`.'), 'y1_st_channel_y1_gate': ('y1_st_channel_y1_gate', 'native SBML value', 'Y1 St Channel Y1 Gate. Maps to SBML symbol `y1_st_channel_y1_gate`.'), 'y_sr_calcium_pump_y_gate': ('y_SR_calcium_pump_y_gate', 'native SBML value', 'Y SR Calcium Pump Y Gate. Maps to SBML symbol `y_SR_calcium_pump_y_gate`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL1006230108.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
