# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Burghaus2011 - Simulating Rivaroxaban effects on blood coagulation."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Burghaus2011SimulatingRivaroxabanEffectsOnBModel1805140001Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Burghaus2011 - Simulating Rivaroxaban effects on blood coagulation."""

    _SBML_ID = 'MODEL1805140001'
    _TITLE = 'Burghaus2011 - Simulating Rivaroxaban effects on blood coagulation'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['APC', 'APC_alpha1AT', 'alpha1AT', 'APC_a2AP', 'alpha2AP', 'APC_a2MG', 'a2MG', 'APC_PCI', 'PCI', 'APC_PNI', 'PNI', 'ATIII', 'Tm', 'mIIa_ATIII', 'mIIa_Tm', 'mIIa_PCI', 'TF', 'TF_VII', 'VII', 'VIII_lipid', 'VIIIa_lipid', 'VIII', 'VIIIa', 'VIII_vWF', 'VIIIa_vWF', 'IXa_VIIIa_lipid', 'IXa_lipid', 'Phospholipid', 'IXa_VIIIa_X_lipid', 'Xa_lipid', 'VIIIa1_L', 'VIIIa2', 'X_lipid', 'V_lipid', 'Va_lipid', 'V', 'Va', 'Xa', 'Xa_Va_lipid', 'II_lipid', 'Xa_Va_II_lipid', 'mIIa', 'II', 'IIa', 'TF_VIIa', 'VIIa', 'TFPI', 'Xa_TFPI', 'TF_VIIa_Xa', 'TF_VIIa_Xa_TFPI', 'Xa_ATIII', 'Xa_a2MG', 'APC_ATIII', 'Xa_PCI', 'mIIa_a2MG', 'mIIa_alpha1AT', 'HCII', 'mIIa_HCII', 'mIIa_PNI', 'IXa', 'IXa_ATIII', 'IIa_ATIII', 'IIa_a2MG', 'IIa_alpha1AT', 'IIa_HCII', 'IIa_PNI', 'IIa_PCI', 'TF_VIIa_ATIII', 'TF_VIIa_X', 'X', 'IX', 'TF_VIIa_IX', 'TF_VIIa_IX_lipid', 'IX_lipid', 'XIa', 'XIa_lipid', 'Dx9065a_Xa', 'Dx9065a_Xa_lipid', 'XI', 'XI_lipid', 'IIa_Tm_PC', 'PC', 'IIa_Tm', 'mIIa_Tm_PC', 'APC_PS', 'PS', 'Bay59_7939_Xa', 'Bay59_7939', 'Bay59_7939_Xa_lipid', 'Bay59__7939_Xa_Va_lipid', 'Bay59_7939_Bound', 'Bay59_7939_Xa_ATIII', 'APC_PS_VIIIa_lipid', 'APC_PS_VIIIa', 'APC_PS_Va_lipid', 'APC_PS_Va', 'Va_Inhib', 'VIIIa_Inhib', 'Dx9065a', 'Dx9065a_Xa_Va_lipid', 'Dx9065a_Xa_ATIII', 'Dx9065a_Bound', 'Xa_alpha1AT', 'Hep', 'Hep_Bound', 'ATIIIa', 'XIa_ATIII', 'I', 'Ia', 'C1Inh', 'XIa_C1Inh', 'XIa_alpha1AT', 'XIa_alpha2AP', 'PAI1', 'XIa_PAI1', 'vWF', 'IIa_Xim', 'Xim', 'mIIa_Xim', 'IIa_Tm_Xim', 'Xim_Bound', 'XIIa']
    _SPECIES_LABELS = {'APC': 'APC', 'APC_alpha1AT': 'APC_alpha1AT', 'alpha1AT': 'alpha1AT', 'APC_a2AP': 'APC_a2AP', 'alpha2AP': 'alpha2AP', 'APC_a2MG': 'APC_a2MG', 'a2MG': 'a2MG', 'APC_PCI': 'APC_PCI', 'PCI': 'PCI', 'APC_PNI': 'APC_PNI', 'PNI': 'PNI', 'ATIII': 'ATIII', 'Tm': 'Tm', 'mIIa_ATIII': 'mIIa_ATIII', 'mIIa_Tm': 'mIIa_Tm', 'mIIa_PCI': 'mIIa_PCI', 'TF': 'TF', 'TF_VII': 'TF_VII', 'VII': 'VII', 'VIII_lipid': 'VIII_lipid', 'VIIIa_lipid': 'VIIIa_lipid', 'VIII': 'VIII', 'VIIIa': 'VIIIa', 'VIII_vWF': 'VIII_vWF', 'VIIIa_vWF': 'VIIIa_vWF', 'IXa_VIIIa_lipid': 'IXa_VIIIa_lipid', 'IXa_lipid': 'IXa_lipid', 'Phospholipid': 'Phospholipid', 'IXa_VIIIa_X_lipid': 'IXa_VIIIa_X_lipid', 'Xa_lipid': 'Xa_lipid', 'VIIIa1_L': 'VIIIa1_L', 'VIIIa2': 'VIIIa2', 'X_lipid': 'X_lipid', 'V_lipid': 'V_lipid', 'Va_lipid': 'Va_lipid', 'V': 'V', 'Va': 'Va', 'Xa': 'Xa', 'Xa_Va_lipid': 'Xa_Va_lipid', 'II_lipid': 'II_lipid', 'Xa_Va_II_lipid': 'Xa_Va_II_lipid', 'mIIa': 'mIIa', 'II': 'II', 'IIa': 'IIa', 'TF_VIIa': 'TF_VIIa', 'VIIa': 'VIIa', 'TFPI': 'TFPI', 'Xa_TFPI': 'Xa_TFPI', 'TF_VIIa_Xa': 'TF_VIIa_Xa', 'TF_VIIa_Xa_TFPI': 'TF_VIIa_Xa_TFPI', 'Xa_ATIII': 'Xa_ATIII', 'Xa_a2MG': 'Xa_a2MG', 'APC_ATIII': 'APC_ATIII', 'Xa_PCI': 'Xa_PCI', 'mIIa_a2MG': 'mIIa_a2MG', 'mIIa_alpha1AT': 'mIIa_alpha1AT', 'HCII': 'HCII', 'mIIa_HCII': 'mIIa_HCII', 'mIIa_PNI': 'mIIa_PNI', 'IXa': 'IXa', 'IXa_ATIII': 'IXa_ATIII', 'IIa_ATIII': 'IIa_ATIII', 'IIa_a2MG': 'IIa_a2MG', 'IIa_alpha1AT': 'IIa_alpha1AT', 'IIa_HCII': 'IIa_HCII', 'IIa_PNI': 'IIa_PNI', 'IIa_PCI': 'IIa_PCI', 'TF_VIIa_ATIII': 'TF_VIIa_ATIII', 'TF_VIIa_X': 'TF_VIIa_X', 'X': 'X', 'IX': 'IX', 'TF_VIIa_IX': 'TF_VIIa_IX', 'TF_VIIa_IX_lipid': 'TF_VIIa_IX_lipid', 'IX_lipid': 'IX_lipid', 'XIa': 'XIa', 'XIa_lipid': 'XIa_lipid', 'Dx9065a_Xa': 'Dx9065a_Xa', 'Dx9065a_Xa_lipid': 'Dx9065a_Xa_lipid', 'XI': 'XI', 'XI_lipid': 'XI_lipid', 'IIa_Tm_PC': 'IIa_Tm_PC', 'PC': 'PC', 'IIa_Tm': 'IIa_Tm', 'mIIa_Tm_PC': 'mIIa_Tm_PC', 'APC_PS': 'APC_PS', 'PS': 'PS', 'Bay59_7939_Xa': 'Bay59_7939_Xa', 'Bay59_7939': 'Bay59_7939', 'Bay59_7939_Xa_lipid': 'Bay59_7939_Xa_lipid', 'Bay59__7939_Xa_Va_lipid': 'Bay59_\xad7939_Xa_Va_lipid', 'Bay59_7939_Bound': 'Bay59_7939_Bound', 'Bay59_7939_Xa_ATIII': 'Bay59_7939_Xa_ATIII', 'APC_PS_VIIIa_lipid': 'APC_PS_VIIIa_lipid', 'APC_PS_VIIIa': 'APC_PS_VIIIa', 'APC_PS_Va_lipid': 'APC_PS_Va_lipid', 'APC_PS_Va': 'APC_PS_Va', 'Va_Inhib': 'Va_Inhib', 'VIIIa_Inhib': 'VIIIa_Inhib', 'Dx9065a': 'Dx9065a', 'Dx9065a_Xa_Va_lipid': 'Dx9065a_Xa_Va_lipid', 'Dx9065a_Xa_ATIII': 'Dx9065a_Xa_ATIII', 'Dx9065a_Bound': 'Dx9065a_Bound', 'Xa_alpha1AT': 'Xa_alpha1AT', 'Hep': 'Hep', 'Hep_Bound': 'Hep_Bound', 'ATIIIa': 'ATIIIa', 'XIa_ATIII': 'XIa_ATIII', 'I': 'I', 'Ia': 'Ia', 'C1Inh': 'C1Inh', 'XIa_C1Inh': 'XIa_C1Inh', 'XIa_alpha1AT': 'XIa_alpha1AT', 'XIa_alpha2AP': 'XIa_alpha2AP', 'PAI1': 'PAI1', 'XIa_PAI1': 'XIa_PAI1', 'vWF': 'vWF', 'IIa_Xim': 'IIa_Xim', 'Xim': 'Xim', 'mIIa_Xim': 'mIIa_Xim', 'IIa_Tm_Xim': 'IIa_Tm_Xim', 'Xim_Bound': 'Xim_Bound', 'XIIa': 'XIIa'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_alpha1_at': ('alpha1AT', 2.45e-05, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `alpha1AT`.'), 'initial_a2_mg': ('a2MG', 3.11e-06, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `a2MG`.'), 'initial_apc_a2_ap': ('APC_a2AP', 9e-07, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `APC_a2AP`.'), 'initial_v_wf': ('vWF', 3.5e-08, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `vWF`.'), 'initial_m_i_ia_alpha1_at': ('mIIa_alpha1AT', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `mIIa_alpha1AT`.'), 'initial_m_i_ia_a2_mg': ('mIIa_a2MG', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `mIIa_a2MG`.')}
    _HEADLINE_OUTPUTS = {'alpha1_at': ('alpha1AT', 'native SBML value', 'alpha1AT. Maps to SBML symbol `alpha1AT`.'), 'a2_mg': ('a2MG', 'native SBML value', 'a2MG. Maps to SBML symbol `a2MG`.'), 'apc_a2_ap': ('APC_a2AP', 'native SBML value', 'APC_a2AP. Maps to SBML symbol `APC_a2AP`.'), 'v_wf': ('vWF', 'native SBML value', 'vWF. Maps to SBML symbol `vWF`.'), 'm_i_ia_alpha1_at': ('mIIa_alpha1AT', 'native SBML value', 'mIIa_alpha1AT. Maps to SBML symbol `mIIa_alpha1AT`.'), 'm_i_ia_a2_mg': ('mIIa_a2MG', 'native SBML value', 'mIIa_a2MG. Maps to SBML symbol `mIIa_a2MG`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL1805140001.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
