# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Proctor2013 - Cartilage breakdown, interventions to reduce collagen release."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Proctor2013CartilageBreakdownInterventionsToBiomd0000000504Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Proctor2013 - Cartilage breakdown, interventions to reduce collagen release."""

    _SBML_ID = 'BIOMD0000000504'
    _TITLE = 'Proctor2013 - Cartilage breakdown, interventions to reduce collagen release'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['ADAMTS4_mRNA', 'cFos', 'cFos_mRNA', 'cJun', 'cJun_mRNA', 'DUSP16', 'IRAK2', 'IRAK2_TRAF6', 'IRAK2_TRAF6_PP4', 'JAK1', 'JAK1_P', 'JNK', 'JNK_P', 'Matriptase', 'MKP1', 'MMP1_mRNA', 'MMP3_mRNA', 'MMP13_mRNA', 'p38', 'p38_P', 'PP4', 'proMMP1', 'proMMP3', 'proMMP13', 'PTPRT', 'SOCS3', 'SOCS3_mRNA', 'STAT3_cyt', 'STAT3_P_cyt', 'TIMP1_mRNA', 'TIMP3_mRNA', 'TRAF6', 'TRAF6_PP4', 'ADAMTS4', 'ADAMTS4_TIMP1', 'ADAMTS4_TIMP3', 'Aggrecan', 'Aggrecan_Collagen2', 'AggFrag', 'ColFrag', 'Collagen2', 'IL1', 'MMP1', 'MMP1_TIMP1', 'MMP1_TIMP3', 'MMP3', 'MMP3_TIMP1', 'MMP3_TIMP3', 'MMP13', 'MMP13_TIMP1', 'MMP13_TIMP3', 'OSM', 'TIMP1', 'TIMP3', 'IL1_IL1R', 'IL1_IL1Ra', 'IL1_IL1R_IRAK2', 'IL1R', 'IL1Ra', 'OSM_OSMR', 'OSM_OSMRa', 'OSMR_SOCS3', 'OSMR', 'OSMRa', 'cFos_cJun', 'cFos_P', 'cJun_P', 'cJun_dimer', 'SP1', 'SP1_TIMP1_DNA', 'STAT3_nuc', 'STAT3_P_nuc', 'TIMP1_DNA']
    _SPECIES_LABELS = {'ADAMTS4_mRNA': 'ADAMTS4 MRNA', 'cFos': 'CFos', 'cFos_mRNA': 'CFos MRNA', 'cJun': 'CJun', 'cJun_mRNA': 'CJun MRNA', 'DUSP16': 'DUSP16', 'IRAK2': 'IRAK2', 'IRAK2_TRAF6': 'IRAK2 TRAF6', 'IRAK2_TRAF6_PP4': 'IRAK2 TRAF6 PP4', 'JAK1': 'JAK1', 'JAK1_P': 'JAK1 P', 'JNK': 'JNK', 'JNK_P': 'JNK P', 'Matriptase': 'Matriptase', 'MKP1': 'MKP1', 'MMP1_mRNA': 'MMP1 MRNA', 'MMP3_mRNA': 'MMP3 MRNA', 'MMP13_mRNA': 'MMP13 MRNA', 'p38': 'P38', 'p38_P': 'P38 P', 'PP4': 'PP4', 'proMMP1': 'ProMMP1', 'proMMP3': 'ProMMP3', 'proMMP13': 'ProMMP13', 'PTPRT': 'PTPRT', 'SOCS3': 'SOCS3', 'SOCS3_mRNA': 'SOCS3 MRNA', 'STAT3_cyt': 'STAT3 Cyt', 'STAT3_P_cyt': 'STAT3 P Cyt', 'TIMP1_mRNA': 'TIMP1 MRNA', 'TIMP3_mRNA': 'TIMP3 MRNA', 'TRAF6': 'TRAF6', 'TRAF6_PP4': 'TRAF6 PP4', 'ADAMTS4': 'ADAMTS4', 'ADAMTS4_TIMP1': 'ADAMTS4 TIMP1', 'ADAMTS4_TIMP3': 'ADAMTS4 TIMP3', 'Aggrecan': 'Aggrecan', 'Aggrecan_Collagen2': 'Aggrecan Collagen2', 'AggFrag': 'AggFrag', 'ColFrag': 'ColFrag', 'Collagen2': 'Collagen2', 'IL1': 'IL1', 'MMP1': 'MMP1', 'MMP1_TIMP1': 'MMP1 TIMP1', 'MMP1_TIMP3': 'MMP1 TIMP3', 'MMP3': 'MMP3', 'MMP3_TIMP1': 'MMP3 TIMP1', 'MMP3_TIMP3': 'MMP3 TIMP3', 'MMP13': 'MMP13', 'MMP13_TIMP1': 'MMP13 TIMP1', 'MMP13_TIMP3': 'MMP13 TIMP3', 'OSM': 'OSM', 'TIMP1': 'TIMP1', 'TIMP3': 'TIMP3', 'IL1_IL1R': 'IL1 IL1R', 'IL1_IL1Ra': 'IL1 IL1Ra', 'IL1_IL1R_IRAK2': 'IL1 IL1R IRAK2', 'IL1R': 'IL1R', 'IL1Ra': 'IL1Ra', 'OSM_OSMR': 'OSM OSMR', 'OSM_OSMRa': 'OSM OSMRa', 'OSMR_SOCS3': 'OSMR SOCS3', 'OSMR': 'OSMR', 'OSMRa': 'OSMRa', 'cFos_cJun': 'CFos CJun', 'cFos_P': 'CFos P', 'cJun_P': 'CJun P', 'cJun_dimer': 'CJun Dimer', 'SP1': 'SP1', 'SP1_TIMP1_DNA': 'SP1 TIMP1 DNA', 'STAT3_nuc': 'STAT3 Nuc', 'STAT3_P_nuc': 'STAT3 P Nuc', 'TIMP1_DNA': 'TIMP1 DNA'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_traf6': ('TRAF6', 100.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `TRAF6`.'), 'initial_stat3_cyt': ('STAT3_cyt', 100.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `STAT3_cyt`.'), 'initial_timp3_mrna': ('TIMP3_mRNA', 20.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `TIMP3_mRNA`.'), 'initial_timp1_mrna': ('TIMP1_mRNA', 20.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `TIMP1_mRNA`.'), 'initial_c_jun_mrna': ('cJun_mRNA', 5.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `cJun_mRNA`.'), 'initial_traf6_pp4': ('TRAF6_PP4', 0.0, 'native SBML value', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `TRAF6_PP4`.')}
    _HEADLINE_OUTPUTS = {'traf6': ('TRAF6', 'native SBML value', 'TRAF6. Maps to SBML symbol `TRAF6`.'), 'stat3_cyt': ('STAT3_cyt', 'native SBML value', 'STAT3 Cyt. Maps to SBML symbol `STAT3_cyt`.'), 'timp3_mrna': ('TIMP3_mRNA', 'native SBML value', 'TIMP3 MRNA. Maps to SBML symbol `TIMP3_mRNA`.'), 'timp1_mrna': ('TIMP1_mRNA', 'native SBML value', 'TIMP1 MRNA. Maps to SBML symbol `TIMP1_mRNA`.'), 'c_jun_mrna': ('cJun_mRNA', 'native SBML value', 'CJun MRNA. Maps to SBML symbol `cJun_mRNA`.'), 'traf6_pp4': ('TRAF6_PP4', 'native SBML value', 'TRAF6 PP4. Maps to SBML symbol `TRAF6_PP4`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/BIOMD0000000504.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
