# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""Tellurium-backed SBML BioModule wrapper for Heiland2019 - Two compartment model of NAD biosynthesis and consumption."""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Heiland2019TwoCompartmentModelOfNadBiosyntModel1905220002Model(TelluriumSBMLBioModule):
    """Faithful SBML execution wrapper for Heiland2019 - Two compartment model of NAD biosynthesis and consumption."""

    _SBML_ID = 'MODEL1905220002'
    _TITLE = 'Heiland2019 - Two compartment model of NAD biosynthesis and consumption'
    _TIME_UNIT = "model_time"
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = ['Gln_NamPT_compartment', 'DNA_damage_NamPT_compartment', 'DNA_ADPR_NamPT_compartment', 'NADbound_NamPT_compartment', 'H3_ac_NamPT_compartment', 'H3_deac_NamPT_compartment', 'Glu_NamPT_compartment', 'NR_NamPT_compartment', 'Pi_NamPT_compartment', 'NaAD_NamPT_compartment', '_1_methyl_NAM_NamPT_compartment', 'H2O_NamPT_compartment', 'PPi_NamPT_compartment', 'AMP_NamPT_compartment', 'NMN_NamPT_compartment', 'NA_NamPT_compartment', 'NaMN_NamPT_compartment', 'ADP_NamPT_compartment', 'SAM_NamPT_compartment', 'SAH_NamPT_compartment', 'NAM_NamPT_compartment', 'NAD_NamPT_compartment', 'NAR_NamPT_compartment', 'PRPP_NamPT_compartment', 'ATP_NamPT_compartment', 'Gln_NADA_compartment', 'DNA_damage_NADA_compartment', 'DNA_ADPR_NADA_compartment', 'NADbound_NADA_compartment', 'H3_ac_NADA_compartment', 'H3_deac_NADA_compartment', 'Glu_NADA_compartment', 'NR_NADA_compartment', 'Pi_NADA_compartment', 'NaAD_NADA_compartment', 'H2O_NADA_compartment', 'PPi_NADA_compartment', 'AMP_NADA_compartment', 'NMN_NADA_compartment', 'NA_NADA_compartment', 'NaMN_NADA_compartment', 'ADP_NADA_compartment', 'NAM_NADA_compartment', 'NAD_NADA_compartment', 'NAR_NADA_compartment', 'PRPP_NADA_compartment', 'ATP_NADA_compartment', 'Nam_ex']
    _SPECIES_LABELS = {'Gln_NamPT_compartment': 'Gln', 'DNA_damage_NamPT_compartment': 'DNA_damage', 'DNA_ADPR_NamPT_compartment': 'DNA_ADPR', 'NADbound_NamPT_compartment': 'NADbound', 'H3_ac_NamPT_compartment': 'H3_ac', 'H3_deac_NamPT_compartment': 'H3_deac', 'Glu_NamPT_compartment': 'Glu', 'NR_NamPT_compartment': 'NR', 'Pi_NamPT_compartment': 'Pi', 'NaAD_NamPT_compartment': 'NaAD', '_1_methyl_NAM_NamPT_compartment': '1-methyl-NAM', 'H2O_NamPT_compartment': 'H2O', 'PPi_NamPT_compartment': 'PPi', 'AMP_NamPT_compartment': 'AMP', 'NMN_NamPT_compartment': 'NMN', 'NA_NamPT_compartment': 'NA', 'NaMN_NamPT_compartment': 'NaMN', 'ADP_NamPT_compartment': 'ADP', 'SAM_NamPT_compartment': 'SAM', 'SAH_NamPT_compartment': 'SAH', 'NAM_NamPT_compartment': 'NAM', 'NAD_NamPT_compartment': 'NAD', 'NAR_NamPT_compartment': 'NAR', 'PRPP_NamPT_compartment': 'PRPP', 'ATP_NamPT_compartment': 'ATP', 'Gln_NADA_compartment': 'Gln', 'DNA_damage_NADA_compartment': 'DNA_damage', 'DNA_ADPR_NADA_compartment': 'DNA_ADPR', 'NADbound_NADA_compartment': 'NADbound', 'H3_ac_NADA_compartment': 'H3_ac', 'H3_deac_NADA_compartment': 'H3_deac', 'Glu_NADA_compartment': 'Glu', 'NR_NADA_compartment': 'NR', 'Pi_NADA_compartment': 'Pi', 'NaAD_NADA_compartment': 'NaAD', 'H2O_NADA_compartment': 'H2O', 'PPi_NADA_compartment': 'PPi', 'AMP_NADA_compartment': 'AMP', 'NMN_NADA_compartment': 'NMN', 'NA_NADA_compartment': 'NA', 'NaMN_NADA_compartment': 'NaMN', 'ADP_NADA_compartment': 'ADP', 'NAM_NADA_compartment': 'NAM', 'NAD_NADA_compartment': 'NAD', 'NAR_NADA_compartment': 'NAR', 'PRPP_NADA_compartment': 'PRPP', 'ATP_NADA_compartment': 'ATP', 'Nam_ex': 'Nam_ex'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_model_state_sah': ('SAH_NamPT_compartment', 1.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `SAH_NamPT_compartment`.'), 'initial_model_state_pi': ('Pi_NamPT_compartment', 1.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Pi_NamPT_compartment`.'), 'initial_model_state_pi_2': ('Pi_NADA_compartment', 1.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Pi_NADA_compartment`.'), 'initial_prpp': ('PRPP_NamPT_compartment', 1.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `PRPP_NamPT_compartment`.'), 'initial_prpp_2': ('PRPP_NADA_compartment', 1.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `PRPP_NADA_compartment`.'), 'initial_nam_ex': ('Nam_ex', 1.0, 'substance', 'Source state initial condition exposed as a model-specific control because no explicit intervention parameter is identifiable. Maps to SBML symbol `Nam_ex`.')}
    _HEADLINE_OUTPUTS = {'sah': ('SAH_NamPT_compartment', 'substance', 'SAH. Maps to SBML symbol `SAH_NamPT_compartment`.'), 'model_state_pi': ('Pi_NamPT_compartment', 'substance', 'Pi. Maps to SBML symbol `Pi_NamPT_compartment`.'), 'model_state_pi_2': ('Pi_NADA_compartment', 'substance', 'Pi. Maps to SBML symbol `Pi_NADA_compartment`.'), 'prpp': ('PRPP_NamPT_compartment', 'substance', 'PRPP. Maps to SBML symbol `PRPP_NamPT_compartment`.'), 'prpp_2': ('PRPP_NADA_compartment', 'substance', 'PRPP. Maps to SBML symbol `PRPP_NADA_compartment`.'), 'nam_ex': ('Nam_ex', 'substance', 'Nam_ex. Maps to SBML symbol `Nam_ex`.')}
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True
    _EXPOSE_INTEGRATION_STEP_INPUT = False

    def __init__(self, model_path: str = 'data/MODEL1905220002.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
